# Generated by Django 4.2.4 on 2023-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentRoutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
